### ISSUE TITLE
error happens when use this tool

### ISSUE THREAD

**Issue by jimchen2018** [BUG1989/caffe-int8-convert-tools#2]
I don't know if calibration image data format is not correct.  
```bash
Quantize the Activation:
/usr/local/lib/python3.5/dist-packages/skimage/io/_io.py:49: UserWarning: `as_grey` has been deprecated in favor of `as_gray`
  warn('`as_grey` has been deprecated in favor of `as_gray`')
Traceback (most recent call last):
  File "caffe-int8-convert-tool.py", line 468, in <module>
    main()
  File "caffe-int8-convert-tool.py", line 457, in main
    activation_quantize(net, transformer, images_files)
  File "caffe-int8-convert-tool.py", line 350, in activation_quantize
    net_forward(net, image, transformer)
  File "caffe-int8-convert-tool.py", line 220, in net_forward
    image = caffe.io.load_image(image_path)
  File "/home/jim/caffe/python/caffe/io.py", line 296, in load_image
    img = skimage.img_as_float(skimage.io.imread(filename, as_grey=not color)).astype(np.float32)
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/_io.py", line 62, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/manage_plugins.py", line 214, in call_plugin
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/_plugins/pil_plugin.py", line 36, in imread
    im = Image.open(f)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2295, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BufferedReader name='/home/jim/data/VOCdevkit/VOC0712/lmdb/VOC0712_trainval_lmdb/lock.mdb'>
```

**Comment by jimchen2018** [comment]
Ok. I see. Thanks a lot!
